
# PostgreSQL db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Harish@2006

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# sql query console config - show on terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=c3BsaXR3aXNlLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbi0yMDI0
jwt.expiration=86400000

server.port=8080